# Generated by Django 3.1.6 on 2021-02-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=5000)),
                ('min_bid', models.IntegerField()),
                ('time_create', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('isactive', models.BooleanField()),
            ],
        ),
    ]
