# Generated by Django 3.1.6 on 2021-02-28 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='listings',
            new_name='listing',
        ),
    ]
