# Generated by Django 3.1.6 on 2021-02-28 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210228_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='min_bid',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='time_create',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='time_end',
        ),
    ]
