# Generated by Django 3.1.6 on 2021-02-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210228_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='description',
        ),
        migrations.AddField(
            model_name='listing',
            name='min_bid',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='listing',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
    ]
